const nodemailer = require("nodemailer");

const sendWelcomeEmail = async (userEmail, userName) => {
  // ១. រៀបចំភ្នាក់ងារផ្ញើសំបុត្រ (Transporter)
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER, // ត្រូវប្រាកដថាមានក្នុង .env
      pass: process.env.EMAIL_PASS, // កូដ ១៦ ខ្ទង់ដែលគ្មានដកឃ្លា
    },
  });

  // ឆែកមើលបណ្តាញភ្ជាប់ (Debug Only) - បង្ហាញក្នុង Terminal បងប្រូ
  transporter.verify(function (error, success) {
    if (error) {
      console.log("❌ SMTP Connection Error: ", error.message);
    } else {
      console.log("✅ Neural Mail Server is Ready!");
    }
  });

  // ២. រចនាសំបុត្រឱ្យឡូយបែប Neural 2026
  const mailOptions = {
    from: '"AI DEV SUITE 🚀" <noreply@neural.link>',
    to: userEmail,
    subject: "ស្វាគមន៍មកកាន់បណ្តាញ Neural Network បងប្រូ! 🦾",
    html: `
            <div style="font-family: sans-serif; background: #020617; color: white; padding: 40px; border-radius: 30px; border: 1px solid rgba(168, 85, 247, 0.2); max-width: 600px; margin: auto;">
                <div style="text-align: center; margin-bottom: 30px;">
                    <h1 style="color: #a855f7; font-size: 28px; font-style: italic; font-weight: 900; letter-spacing: -1px;">AI DEV SUITE V2.6</h1>
                    <p style="font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 4px;">Neural Network Identity Verified</p>
                </div>
                
                <div style="background: rgba(15, 23, 42, 0.5); padding: 30px; border-radius: 20px; border: 1px solid rgba(255, 255, 255, 0.05);">
                    <p style="font-size: 16px;">សួស្តីបងប្រូ <b>${userName}</b>! 🦾</p>
                    <p style="color: #94a3b8; line-height: 1.6;">អបអរសាទរ! គណនីរបស់អ្នកត្រូវបានបង្កើតក្នុង <b>MongoDB Atlas</b> ជោគជ័យហើយ។ ឥឡូវនេះបងអាចប្រើប្រាស់មហិទ្ធិឫទ្ធិ AI ទាំងអស់ក្នុងប្រព័ន្ធរបស់យើងបានតាមចិត្ត។</p>
                    
                    <div style="margin: 30px 0; border-left: 4px solid #a855f7; padding-left: 20px;">
                        <p style="font-size: 12px; color: #a855f7; font-weight: bold; margin-bottom: 5px;">តើបងអាចធ្វើអ្វីបានខ្លះ?</p>
                        <p style="font-size: 11px; color: #cbd5e1; margin: 5px 0;">✅ សួរ AI លើផ្នែកវប្បធម៌ និងការសិក្សា (Culture & Tutor)</p>
                        <p style="font-size: 11px; color: #cbd5e1; margin: 5px 0;">✅ រក្សាទុកដានជើងមេរៀនក្នុង Archive</p>
                        <p style="font-size: 11px; color: #cbd5e1; margin: 5px 0;">✅ គ្រប់គ្រងអត្តសញ្ញាណ Cyber Profile</p>
                    </div>

                    <a href="http://localhost:3000/login" style="display: block; text-align: center; background: #a855f7; color: black; padding: 15px; border-radius: 12px; text-decoration: none; font-weight: bold; font-size: 12px; margin-top: 20px;">ACCESS CONTROL CENTER</a>
                </div>

                <div style="text-align: center; margin-top: 40px; border-top: 1px solid rgba(255,255,255,0.05); padding-top: 20px;">
                    <p style="font-size: 9px; color: #475569; text-transform: uppercase; letter-spacing: 2px;">Generated by Neural System 2026 | Assignment for Mr. Bundouern</p>
                </div>
            </div>
        `,
  };

  // ៣. ធ្វើការផ្ញើចេញ
  try {
    await transporter.sendMail(mailOptions);
    console.log("📧 Welcome Email Sent Successfully to: " + userEmail);
  } catch (error) {
    console.error("❌ Nodemailer Error: ", error.message);
  }
};

module.exports = sendWelcomeEmail;
